global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
         - prometheus:9090
  - job_name: 'discovery_server'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: [ 'discovery-server:8080' ]
        labels:
          application: 'Discovery Server Application'
  - job_name: 'api_gateway'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: [ 'api-gateway:8080' ]
        labels:
          application: 'API gateway Application'
  - job_name: 'product_service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['product-service:8080']
        labels:
          application: 'Product Service Application'
  - job_name: 'order_service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory_service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['inventory-service:8080']
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification_service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'